[project]
name = "detailed-plan-1"
version = "0.1.0"
description = "Project for detailed-plan-1"
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
