[project]
name = "secure_llmattacks_v3"
version = "0.1.0"
description = "Secure LLM Attacks v3"
readme = "README.md"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
