[project]
name = "secure-llmattacks-v3"
version = "0.1.0"
description = "Research workspace for secure LLM attack detection"
authors = [{name = "LLM Security"}]
readme = "README.md"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
