name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black mypy pytest pytest-cov
      - name: Black check
        run: black --check .
      - name: Run tests
        run: |
          FAST_LINK_CHECK=10 pytest -q --cov=. --cov-report=xml
      - name: Validate dataset schema
        run: python scripts/build_dataset.py --check-only
      - name: Mypy
        run: mypy --strict .
      - name: Post coverage comment
        uses: MishaKav/pytest-coverage-comment@v1
        with:
          pytest-xml-coverage-path: ./coverage.xml
