name: Link Checker

on:
  push:
    paths:
      - '**/*.md'
      - '**/*.html'
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.html'
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress README.md docs/**/*.md docs/**/*.html
