name: Refresh Links

on:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
      - name: Refresh link archive
        run: python scripts/refresh_links.py
      - name: Commit updates
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add link_archive.json
          if git diff --cached --quiet; then
            echo 'No changes to commit'
          else
            git commit -m 'chore: refresh link archive'
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
